"""Generates the LLM prompt for scene authoring.

The vocabulary (materials, frictions, presets, assemblies, fields) is pulled
from the live preset tables, so the prompt can never advertise a material that
the compiler does not know. Regenerate with::

    python -m mjscene prompt --write        # -> ai/PROMPT.md
"""

from __future__ import annotations

from .. import library
from ..spec import NODES
from ..spec import assemblies as _assemblies

__all__ = ["build_prompt"]

_GENERATOR_DOC = {
    "wood_planks": "Staggered wood planks with seams, grain, and color variation",
    "fabric_weave": "Plain weave with warp and weft, yarn variation, and broad undulation",
    "rounded_box": "Rounded box for soft furniture such as mattresses and cushions",
}

GENERATORS_EXAMPLE = """```jsonc
"materials": [{ "name": "floor", "rgba": [1,1,1,1],
                "texture": { "generator": "wood_planks", "params": { "seed": 3 } },
                "texrepeat": [3, 3], "texuniform": true }],
"meshes":    [{ "name": "cushion", "generator": "rounded_box",
                "params": { "size": [0.6, 0.64, 0.11], "radius": 0.05, "uv_tiles": 9 } }],
"objects":   [{ "name": "seat", "shape": "mesh", "mesh": "cushion", "pos": [0,0,0.5] }]
```"""

HEADER = """# System prompt: MuJoCo scene generation (mjscene spec v1)

> Generated by `python -m mjscene prompt --write`. The vocabulary follows the code; do not edit by hand.
> Give the section between "Prompt begins" and "Prompt ends" to an LLM as its system prompt,
> then describe the scene in natural language. Save the resulting JSON as
> `workspace/<scene_name>/scene.json` and run `python -m mjscene build <scene_name> --smoke 3`.

---
## Prompt begins
"""

FOOTER = """
## Prompt ends
---

## Suggested conversation

```
Create a 6 x 4 meter indoor room for AMR navigation: polished slippery floor,
two shelf rows, ten scattered cardboard boxes, warm ceiling lights, and an overhead camera.
```

After the model returns JSON:

```bash
python -m mjscene build <scene_name> --smoke 3
```

If the build fails, give the model the **full error output** so it can repair the spec.
The validator messages are written for this feedback loop.
"""

RULES = """
You author MuJoCo robot simulation scenes. Given a natural-language request, output exactly
**one JSON object** (mjscene spec v1). Do not output MJCF/XML, explanatory text, or markdown fences.

## Rule 0: Produce a scene without changing the framework

Your output belongs in `workspace/<scene_name>/scene.json` and its sibling `assets/` directory.
Treat framework code (`mjscene/`, `web/`, `schemas/`) as read-only:

- Define new colors in the spec's `materials` instead of changing the preset library.
- Define new friction in `friction_profiles`.
- Use `raw_mjcf` for MJCF features that the spec does not cover.
- Put custom meshes and textures in `assets/` and reference relative paths such as `"assets/xxx.obj"`.
- Never hand-edit generated files in `build/`.

If the request truly requires a framework change, explain why and ask before changing it.

## Required rules

1. Coordinates are **Z-up**; units are meters, kilograms, seconds, and degrees. Ground is z=0.
2. Every `size` uses a **half-size or radius**. A 0.4 m cube uses `"size": [0.2, 0.2, 0.2]`;
   `sphere=[r]`, `capsule/cylinder=[r, half-length]`, `box/ellipsoid=[x, y, z]`.
3. A dynamic object's `pos[2]` must be at least its half-height + 0.01 to avoid ground overlap.
   Add tabletop height for objects placed on tables or platforms.
4. Choose one rotation form: `euler` (degrees), `quat` ([w,x,y,z]), or `axisangle`.
5. Keep names globally unique across objects, cameras, and materials.
6. Friction has `[sliding, torsional, rolling]` values. Torsional needs `condim>=4`;
   rolling needs `condim>=6`. A ball or cylinder needs rolling friction and `condim: 6` to settle.
7. Limit shadow-casting lights to two or three; set `"castshadow": false` on other lights.
8. Use only listed presets. Define and reference new colors or friction in `materials` or
   `friction_profiles`; materials can inherit with `"base": "<preset_name>"`.
9. Prefer `assemblies` for rooms, tables, shelves, stairs, ramps, bins, and scattered objects.
   Use `rounded_box` for soft furniture such as mattresses and cushions; MuJoCo boxes have sharp edges.
10. Include lighting, ground, sky, at least one dynamic object, explicit friction or collision settings,
    and at least one camera view.
11. Omit uncertain fields and use their defaults. Do not invent field names.
12. Every walkable road, lawn, bridge and ramp needs collision support at its visible elevation. Decorative noncolliding geometry cannot support a robot. Do not use a lower hidden plane for an elevated road or convex-hull collision on an entire material-merged scene mesh. Use suitable primitives, heightfields or reviewed collision decomposition.
13. Spawn is a support-floor point at the actual local elevation; apply the robot base offset separately. Raising spawn alone cannot fix missing collisions. Check support, visible/collision alignment, footprint and ramp transitions. Native loading alone is not dynamics acceptance; perform a short intended-controller run before claiming the scene is runnable.
"""

SHAPE_NOTE = """
## Top-level structure

```jsonc
{
  "$schema": "../../schemas/scene.schema.json",
  "name": "snake_case_id",          // Required; match the folder name under workspace/
  "title": "Readable title",
  "description": "What this scene tests",
  "tags": ["indoor", "mobile-robot"],
  "physics":  { ... }, "sky": { ... }, "lighting": { ... }, "ground": { ... },
  "defaults": { ... }, "materials": [ ... ], "friction_profiles": [ ... ],
  "meshes":   [ ... ], "assemblies": [ ... ], "objects": [ ... ],
  "contacts": { "pairs": [ ... ], "excludes": [ ... ] },
  "robots":   [ ... ], "cameras": [ ... ], "viewer": { ... }
}
```
"""

EXAMPLE = """
## Complete example (follow this style)

```json
{
  "$schema": "../../schemas/scene.schema.json",
  "name": "pick_station",
  "title": "Sorting Station",
  "description": "A conveyor-side pick station where the robot places parcels into a bin.",
  "tags": ["indoor", "manipulation"],
  "physics": { "timestep": 0.001, "integrator": "implicitfast", "cone": "elliptic",
               "impratio": 40, "noslip_iterations": 8 },
  "sky": { "preset": "indoor" },
  "lighting": { "preset": "warehouse", "shadow_quality": "high",
                "extra_lights": [
                  { "name": "task_light", "type": "spot", "pos": [0, -1.2, 2.4],
                    "target": [0, 0, 0.8], "cutoff": 40, "exponent": 12,
                    "diffuse": [0.5, 0.5, 0.48], "castshadow": false } ] },
  "ground": { "type": "plane", "size": [10, 10], "material": "concrete",
              "friction": "concrete", "condim": 3 },
  "defaults": { "condim": 4, "friction": "cardboard", "contact": "default" },
  "materials": [ { "name": "tote_blue", "base": "plastic_blue", "roughness": 0.45 } ],
  "assemblies": [
    { "type": "conveyor", "name": "belt", "pos": [0, 0, 0], "size": [3.0, 0.7, 0.75] },
    { "type": "bin", "name": "tote", "pos": [1.1, -0.9, 0], "size": [0.5, 0.35, 0.22],
      "material": "tote_blue" },
    { "type": "target_pad", "name": "goal", "pos": [1.1, -0.9, 0.24], "size": [0.12] }
  ],
  "objects": [
    { "name": "parcel", "shape": "box", "size": [0.12, 0.09, 0.07], "pos": [-0.8, 0, 1.0],
      "euler": [0, 0, 15], "material": "cardboard", "friction": "cardboard",
      "mass": 1.2, "condim": 4, "tags": ["target"] },
    { "name": "can", "shape": "cylinder", "size": [0.033, 0.06], "pos": [-0.3, 0.1, 0.95],
      "material": "aluminium", "friction": "greased_metal", "mass": 0.35, "condim": 6 }
  ],
  "cameras": [
    { "name": "cam_overview", "pos": [2.5, -2.5, 2.0], "target": [0, 0, 0.8], "fovy": 50 },
    { "name": "cam_wrist", "pos": [0, -0.6, 1.5], "target": [0, 0, 0.78], "fovy": 45 }
  ],
  "viewer": { "camera_pos": [3.0, -3.2, 2.2], "camera_target": [0, 0, 0.8],
              "show_contacts": true }
}
```
"""

TUNING = """
## Choose parameters by task

| Task | Physics | Objects and ground |
| --- | --- | --- |
| Tabletop grasping | `timestep 0.001`, `cone elliptic`, `impratio 50`, `noslip_iterations 10` | `condim 6` with `grippy_rubber` or `silicone` friction |
| Stacking or dense contact | `timestep 0.002`, `impratio 10` | `defaults.contact "soft"`, `condim 4` |
| Wheeled or AMR navigation | defaults | `concrete` or `polished_floor` ground, `rubber` wheels, `condim 4` |
| Legged obstacle crossing | `timestep 0.002`, `cone elliptic`, `iterations 150` | `ground.type "heightfield"` and `obstacle_course` assembly |
| Slip and low-friction studies | `impratio 1` | `ice`, `greased_metal`, or `polished_floor` ground |
| Quick preview of a large scene | `timestep 0.004`, `integrator implicitfast` | Use `condim 6` sparingly and one shadow light |
"""


def _fmt_materials() -> str:
    rows = []
    for name, m in library.MATERIALS.items():
        rgba = m.get("rgba", [0.7, 0.7, 0.7, 1])
        extra = []
        if m.get("texture"):
            extra.append("textured")
        if m.get("metallic") is not None:
            extra.append("metallic")
        if len(rgba) > 3 and rgba[3] < 1:
            extra.append("translucent")
        rows.append(f"`{name}`" + (f"({'/'.join(extra)})" if extra else ""))
    return ", ".join(rows)


def _fmt_frictions() -> str:
    lines = ["| Name | Sliding | Torsional | Rolling | Suggested condim | Purpose |", "| --- | --- | --- | --- | --- | --- |"]
    for name, f in library.FRICTION.items():
        lines.append(f"| `{name}` | {f['sliding']} | {f['torsional']} | {f['rolling']} | "
                     f"{f['condim']} | {f.get('note', '')} |")
    return "\n".join(lines)


def _fmt_contacts() -> str:
    lines = ["| Name | solref | Characteristics |", "| --- | --- | ---"]
    for name, c in library.CONTACT_PROFILES.items():
        lines.append(f"| `{name}` | {c['solref']} | {c.get('note', 'standard stiffness')} |")
    return "\n".join(lines)


def _fmt_lighting() -> str:
    lines = ["| Preset | Lights | Best for |", "| --- | --- | --- |"]
    fit = {"noon": "Outdoor noon", "afternoon": "Outdoor afternoon with long shadows", "sunset": "Warm low-angle light",
           "night_moon": "Outdoor night", "warehouse": "Factory or warehouse interior",
           "indoor_office": "Office or home interior", "studio_3point": "Three-point product lighting and close-up grasping",
           "flat": "Shadow-free flat light for debugging"}
    for name, l in library.LIGHTING.items():
        kinds = " + ".join(f"{x['type']}" for x in l["lights"])
        lines.append(f"| `{name}` | {kinds} | {fit.get(name, '')} |")
    return "\n".join(lines)


def _fmt_assemblies() -> str:
    lines = ["| Type | Parameters |", "| --- | --- |"]
    for name in library.ASSEMBLIES:
        lines.append(f"| `{name}` | {_assemblies.DOCS.get(name, '')} |")
    return "\n".join(lines)


def _fmt_generators() -> str:
    lines = [
        "MuJoCo only has checker, gradient, and flat built-in textures, and no rounded box primitive.",
        "Use the framework generators when needed; the compiler creates their assets automatically:", "",
        "| Used in | Generator | Description |", "| --- | --- | --- |",
    ]
    for n in library.TEXTURE_GENERATORS:
        lines.append(f"| `materials[].texture.generator` | `{n}` | {_GENERATOR_DOC.get(n, '')} |")
    for n in library.MESH_GENERATORS:
        lines.append(f"| `meshes[].generator` | `{n}` | {_GENERATOR_DOC.get(n, '')} |")
    lines += ["", GENERATORS_EXAMPLE, "",
              "`rounded_box` uses **full dimensions**, unlike ordinary half-size geoms. Its radius is capped",
              "at half the thinnest side. Text-bearing textures such as signs need external images."]
    return "\n".join(lines)


def _fmt_node(node: str, title: str) -> str:
    lines = [f"**{title}** (`{node}`)", "", "| Field | Type | Default | Description |", "| --- | --- | --- | --- |"]
    for key, f in NODES[node].items():
        kind = f.kind
        if f.kind == "enum":
            kind = " \\| ".join(str(e) for e in (f.enum or []))
        elif f.kind == "ref":
            kind = f"{f.ref} name"
        elif f.kind in ("node", "nodelist"):
            kind = f"{f.node}{'[]' if f.kind == 'nodelist' else ''}"
        dv = "required" if f.required else ("—" if f.default is None else f"`{f.default}`")
        lines.append(f"| `{key}` | {kind} | {dv} | {f.doc} |")
    return "\n".join(lines)


def build_prompt() -> str:
    parts = [
        HEADER,
        RULES,
        SHAPE_NOTE,
        "## Available materials (`material`)\n\n" + _fmt_materials()
        + "\n\nCustom example: `{\"name\": \"x\", \"base\": \"metal\", \"rgba\": [0.9,0.2,0.2,1]}`",
        "## Available friction models (`friction`)\n\n" + _fmt_frictions()
        + "\n\nYou may also use `\"friction\": [1.2, 0.05, 0.005]` directly or define a named model in "
          "`friction_profiles`.",
        "## Contact stiffness (`contact`)\n\n" + _fmt_contacts(),
        "## Sky presets (`sky.preset`)\n\n"
        + ", ".join(f"`{k}`" for k in library.SKY),
        "## Lighting presets (`lighting.preset`)\n\n" + _fmt_lighting(),
        "## Assemblies (`assemblies[].type`)\n\n" + _fmt_assemblies(),
        "## Terrain (`ground.terrain.kind`)\n\n"
        + ", ".join(f"`{k}`" for k in library.TERRAIN_KINDS)
        + "\n\nUse with `ground.type: \"heightfield\"`, `height_scale` (maximum elevation in meters), "
          "and `terrain.seed/frequency/octaves/resolution/flat_radius`.",
        "## Procedural asset generators\n\n" + _fmt_generators(),
        "## Shapes (`objects[].shape`)\n\n" + ", ".join(f"`{s}`" for s in library.SHAPES)
        + "\n\n`none` is a coordinate frame that can hold compound bodies through `children`.",
        "## Field reference\n\n" + "\n\n".join([
            _fmt_node("OBJECT", "Object"),
            _fmt_node("PHYSICS", "Physics"),
            _fmt_node("GROUND", "Ground"),
            _fmt_node("LIGHT", "Single light"),
            _fmt_node("LIGHTING", "Lighting"),
            _fmt_node("SKY", "Sky"),
            _fmt_node("MATERIAL", "Material"),
            _fmt_node("JOINT", "Joint"),
            _fmt_node("CAMERA", "Camera"),
            _fmt_node("CONTACT_PAIR", "Contact pair"),
            _fmt_node("VIEWER", "Viewer"),
        ]),
        TUNING,
        EXAMPLE,
        FOOTER,
    ]
    return "\n\n".join(parts).strip() + "\n"
